#  https://viblo.asia/p/upload-file-len-amazon-s3-su-dung-java-spring-boot-E375zQadlGW
amazonProperties:
  endpointUrl: ${AWS_URL}
  accessKey: ${AWS_ASSESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucketName: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION}
